version: '{build}'
skip_tags: true
image: Visual Studio 2017
configuration: Release
install:
  - ps: mkdir -Force ".\build\" | Out-Null
  
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Serilog.*.nupkg
deploy:
- provider: GitHub
  auth_token:
    secure: 6bcab7cc94d17813f78b8f98d5efcee6fb20c7b4
  artifact: /Serilog.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master